apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverydetails-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverydetails
  template:
    metadata:
      labels:
        app: deliverydetails
    spec:
      containers:
        - name: deliverydetails
          image: sulekh/deliverydetails
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: riseswitchgear 
            - name: MONGO_URI
              value: 'mongodb://deliverydetails-mongo-srv:27017/deliverydetails'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: deliverydetails-srv
spec:
  selector:
    app: deliverydetails
  ports:
    - name: deliverydetails
      protocol: TCP
      port: 3000
      targetPort: 3000