apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: riseswitchgear.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/panels/?(.*)
            pathType: Prefix
            backend:
              service:
                name: panels-srv
                port:
<<<<<<< HEAD
                  number: 3000
          - path: /api/cart/?(.*)
            pathType: Prefix
            backend:
              service:
                name: cart-srv
                port:
                  number: 3000         
=======
                  number: 3000 
>>>>>>> ede338690b4ab569aed5d400bd341eb94f5f3f83
          - path: /api/orders/?(.*)
            pathType: Prefix
            backend:
              service:
                name: orders-srv
                port:
                  number: 3000
          - path: /api/payments/?(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-srv
                port:
                  number: 3000
<<<<<<< HEAD
          - path: /api/deliverydetails/?(.*)
            pathType: Prefix
            backend:
              service:
                name: deliverydetails-srv
                port:
                  number: 3000        
          - path: /?(.*)
            pathType: ImplementationSpecific
=======
          - path: /?(.*)
            pathType: Prefix
>>>>>>> ede338690b4ab569aed5d400bd341eb94f5f3f83
            backend:
              service:
                name: client-srv
                port:
                  number: 3000 